openapi: 3.0.0
info:
  title: Banking API
  version: 1.0.0
  description: Bankining api
  contact:
    email: 
servers:
- description: This the is a simple REST API banking application
  url: https://localhost
  
paths:
  /Accounts:
    get:
      tags:
      - accounts 
      summary: get all accounts
      operationId: getAllAccounts
      description: Calling this will allow Employees to check data of all accounts
      responses:
        '200':
          description: the accounts data
          content:
            application/json:
              schema:
                type: array
                items:
                  anyOf:
                    - $ref: '#/components/schemas/CurrentAccount'
                    - $ref: '#/components/schemas/SavingAccount'
        '404':
          description: accounts are not found
        '400':
          description: bad request (error occured)
    
    post:
      tags:
      - accounts 
      summary: create a bank account
      operationId: createBankAccount
      description: Calling this will allow epmployees to open an account for a specific customer
      requestBody:
        description: create a bank account
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
              
      responses:
        '201':
          description: the account has been created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '400':
          description: account has not been created 
  
  /Accounts/{userId}:
    get:
      tags:
      - accounts 
      summary: get one account
      operationId: getUserAccount
      description: Calling this will allow both customer and employee to check data of a specific account
      parameters:
      - in: path
        name: userId
        required: true
        description: the user id
        schema:
          type: integer
          format: Int64
          minimum: 1
      responses:
        '200':
          description: the account data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
                  
                  anyOf: #to be discussed
                    - $ref: '#/components/schemas/CurrentAccount'
                    - $ref: '#/components/schemas/SavingAccount'
        '400':
          description: invalid user id 
        '404':
          description: account cannot be found
          
  /users/register:
    post:
      tags:
        - Register
      operationId: createNewUser
      summary: Add a new user
      requestBody:
        description: Adding a new user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Log'
          text/plain:
            schema:
              type: string
      responses:
        '201':
          description: Created
        "400":
          description: Unexpected error
          
  /users/login:
    post:
      tags:
        - Login
      operationId: createUserToken
      summary: Returns an auth token
      requestBody:
        description: Logs a user in and return an auth token, if the specified username and password are correct. 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Log'
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: Token send
        "400":
          description: Unexpected error
        "404":
          description: User not found
          
        
components:
  schemas:
    User:
      type: object
      required:
        - id
        - officialName
        - dateOfBirth
        - primaryAddress
        - mobileNumber
        - emailAddress
        - commrcialMessages
      properties:
        id:
          type: integer
        officialName:
          type: string
        preferedName:
          type: string
        sex:
          type: string
          enum: [male, female]
        dateOfBirth:
          type: string
        primaryAddress:
          $ref: '#/components/schemas/Address'
        postAddress:
          $ref: '#/components/schemas/Address'
        mobileNumber:
          type: string
        emailAddress:
          type: string
        commrcialMessages:
          type: string
          enum: [by post, by bankmail, by telephon, by email]
        preferedLanguage:
          type: string
          enum: 
            - Dutch 
            - English
        userType:
          anyOf:    
            - $ref: '#/components/schemas/Employee'
              
            - $ref: '#/components/schemas/Customer'
              
          
      discriminator: 
        propertyName: id
    Customer:
      allOf:    
        - $ref: '#/components/schemas/User'
          
            
    Employee:
      allOf:    
        - $ref: '#/components/schemas/User'
         
      properties:
        jobPosition:
          type: string
            
    Address:
      type: object
      properties:
        street:
          type: string
        houseNumber:
          type: integer
        postCode:
          type: string
        city:
          type: string
        country:
          type: string
    Account:
      type: object
      required:
        - dateOfOpening
        - userId
        - accountType
      properties:
        accountNumber:
          type: string
        balance:
          type: integer
        dateOfOpening:
          type: string
        userId:
          type: integer
    Log:
      type: object
      required:
        - userId
        - userName
        - password
      properties:
        userId:
          type: integer
        accountType: 
          type: string
          enum: ["current","saving"]
  
    CurrentAccount:
      allOf:
        - $ref: '#/components/schemas/Account'
        
    SavingAccount:
      allOf:
        - $ref: '#/components/schemas/Account'
      properties:
        interestRate:
          type: integer
