openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/611034/Login/1.0.0
info:
  description: This is a simple API
  version: "1.0.0"
  title: Simple Inventory API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /users/register:
    post:
      tags:
        - Register
      operationId: createNewUser
      summary: Add a new user
      requestBody:
        description: Adding a new user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Log'
          text/plain:
            schema:
              type: string
      responses:
        '201':
          description: Created
        "400":
          description: Unexpected error
          
  /users/login:
    post:
      tags:
        - Login
      operationId: createUserToken
      summary: Returns an auth token
      requestBody:
        description: Logs a user in and return an auth token, if the specified username and password are correct. 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Log'
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: Token send
        "400":
          description: Unexpected error
        "404":
          description: User not found
        
      
components:
  securitySchemes:
    apikey:         
      type: apiKey
      name: x-authtoken
      in: header
  schemas:
    Log:
      type: object
      required:
        - userId
        - userName
        - password
      properties:
        userId:
          type: integer
        userName:
          type: string
        password:
          type: string